"use client";

import { useEffect, useRef, useState } from "react";
import type {
  GeoJSONSource,
  Map as MlMap,
  MapGeoJSONFeature,
  MapMouseEvent,
  Marker as MlMarker,
} from "maplibre-gl";
import type { FleetTelemetrySnapshot } from "./dispatch-board";

const MAP_CSS_HREF = "/maplibre/maplibre-gl.css";

// OpenFreeMap: free, keyless vector tiles. `liberty` is a clean street style.
const MAP_STYLE = "https://tiles.openfreemap.org/styles/liberty";

/**
 * A distinct color per route index, generated by walking the hue circle at the
 * golden angle (~137.5°) so even 48+ routes stay far apart in hue - adjacent
 * indices never look alike. Lightness alternates slightly for extra separation.
 * Shared with the dispatch sidebar so a route's color matches list and map.
 */
export function routeColor(i: number): string {
  const hue = Math.round((i * 137.508) % 360);
  const light = i % 2 === 0 ? 47 : 58;
  const sat = i % 3 === 0 ? 82 : 68;
  return `hsl(${hue} ${sat}% ${light}%)`;
}

const VEHICLE_COLOR: Record<string, string> = {
  EN_ROUTE: "#f59e0b",
  IDLE: "#94a3b8",
  RETURNING: "#3b82f6",
  STOPPED: "#a855f7",
};

/** Does this browser actually have a usable WebGL context? (maplibre needs one.) */
function webglSupported(): boolean {
  try {
    const c = document.createElement("canvas");
    return !!(c.getContext("webgl2") || c.getContext("webgl") || c.getContext("experimental-webgl"));
  } catch {
    return false;
  }
}

/**
 * A rotatable vehicle marker: a filled navigation chevron pointing "up" (north)
 * that maplibre rotates to the heading, on a soft colored disc. Bold white
 * outline so it reads over any map tile; the selected van gets a ring + halo.
 * The chevron shape makes direction unambiguous at a glance.
 */
function vanEl(color: string, selected: boolean): HTMLElement {
  const size = selected ? 34 : 28;
  const el = document.createElement("div");
  el.style.cssText = `width:${size}px;height:${size}px;cursor:pointer;will-change:transform;filter:drop-shadow(0 1px 2px rgba(0,0,0,.45))`;
  el.innerHTML =
    `<svg viewBox="-14 -14 28 28" width="${size}" height="${size}">` +
    `<circle r="13" fill="${color}" opacity="${selected ? 0.28 : 0.16}"/>` +
    (selected ? `<circle r="13" fill="none" stroke="${color}" stroke-width="2"/>` : "") +
    // Arrowhead + short tail = a clear "pointing" glyph.
    `<path d="M 0 -11 L 8 7 L 0 2.5 L -8 7 Z" fill="${color}" stroke="#fff" stroke-width="1.8" stroke-linejoin="round"/>` +
    `</svg>`;
  return el;
}

// ---- GeoJSON builders --------------------------------------------------------

type LineFC = {
  type: "FeatureCollection";
  features: {
    type: "Feature";
    properties: { color: string; vehicleId: string | null; done: number };
    geometry: { type: "LineString"; coordinates: [number, number][] };
  }[];
};

type PointFC = {
  type: "FeatureCollection";
  features: {
    type: "Feature";
    properties: Record<string, string | number | null>;
    geometry: { type: "Point"; coordinates: [number, number] };
  }[];
};

/**
 * One LineString per route *leg*, tagged done vs. remaining: a leg is "done" once
 * the stop it arrives at is DELIVERED (the return-to-depot leg is always shown as
 * remaining - it's the drive still ahead). This is what lets the map render the
 * portion of a route already driven differently from the part still to go.
 */
function routeLinesGeoJSON(t: FleetTelemetrySnapshot): LineFC {
  const features: LineFC["features"] = [];
  t.routes.forEach((r, i) => {
    const color = routeColor(i);
    const statusById = new Map(r.stops.map((s) => [s.id, s.status]));
    if (r.geometry && r.legs.length) {
      for (const leg of r.legs) {
        if (leg.geometry.length < 2) continue;
        const done = leg.toDeliveryId && statusById.get(leg.toDeliveryId) === "DELIVERED" ? 1 : 0;
        features.push({
          type: "Feature",
          properties: { color, vehicleId: r.vehicleId, done },
          geometry: { type: "LineString", coordinates: leg.geometry },
        });
      }
    } else if (r.stops.length) {
      // No road geometry - straight depot -> stops fallback (single remaining line).
      features.push({
        type: "Feature",
        properties: { color, vehicleId: r.vehicleId, done: 0 },
        geometry: {
          type: "LineString",
          coordinates: [[t.depot.lng, t.depot.lat], ...r.stops.map((s) => [s.lng, s.lat] as [number, number])],
        },
      });
    }
  });
  return { type: "FeatureCollection", features };
}

/** One point per stop, styled by delivery status (delivered stops fade back). */
function stopsGeoJSON(t: FleetTelemetrySnapshot): PointFC {
  const colorByStop = new Map<string, string>();
  const vehicleByStop = new Map<string, string | null>();
  t.routes.forEach((r, i) => {
    const c = routeColor(i);
    for (const s of r.stops) {
      colorByStop.set(s.id, c);
      vehicleByStop.set(s.id, r.vehicleId);
    }
  });
  return {
    type: "FeatureCollection",
    features: t.stops.map((s) => {
      const delivered = s.status === "DELIVERED";
      const failed = s.status === "FAILED";
      const current = s.status === "OUT_FOR_DELIVERY";
      // Color by delivery status so progress reads at a glance (green delivered,
      // red failed, amber current, slate still pending) - the route line keeps
      // the per-route color for association.
      const statusColor = delivered ? "#10b981" : failed ? "#ef4444" : current ? "#f59e0b" : "#64748b";
      return {
        type: "Feature" as const,
        properties: {
          id: s.id,
          seq: s.sequence ?? 0,
          status: s.status,
          color: statusColor,
          routeColor: colorByStop.get(s.id) ?? "#94a3b8",
          vehicleId: vehicleByStop.get(s.id) ?? null,
          customer: s.customer ?? s.orderNumber ?? "Stop",
          address: s.address ?? "",
          r: current ? 6.5 : delivered ? 3.4 : 4.6,
          op: delivered ? 0.55 : 0.95,
          stroke: current ? 2.4 : 1.4,
        },
        geometry: { type: "Point" as const, coordinates: [s.lng, s.lat] },
      };
    }),
  };
}

/**
 * Apply "focus mode" to the route/stop layers for the current selection: when a
 * route is selected everything else fades right back and the selected route is
 * drawn bold, on a white casing, with its stops enlarged + numbered - so one run
 * reads unmistakably out of a tangle of dozens. With nothing selected, all
 * routes show at normal weight. Called on load and on every selection change.
 */
function applyFocus(map: MlMap, selected: string | null) {
  const S = selected ?? "__none__";
  const sel = !!selected;
  if (map.getLayer("routes-casing")) map.setFilter("routes-casing", ["==", ["get", "vehicleId"], S]);
  if (map.getLayer("routes-done")) {
    map.setPaintProperty("routes-done", "line-opacity", ["case", ["==", ["get", "vehicleId"], S], 0.85, sel ? 0.05 : 0.3]);
    map.setPaintProperty("routes-done", "line-width", ["case", ["==", ["get", "vehicleId"], S], 4, 2]);
  }
  if (map.getLayer("routes-remaining")) {
    map.setPaintProperty("routes-remaining", "line-opacity", ["case", ["==", ["get", "vehicleId"], S], 1, sel ? 0.12 : 0.9]);
    map.setPaintProperty("routes-remaining", "line-width", ["case", ["==", ["get", "vehicleId"], S], 6, sel ? 1.6 : 2.8]);
  }
  if (map.getLayer("stops-circle")) {
    map.setPaintProperty("stops-circle", "circle-opacity", ["case", ["==", ["get", "vehicleId"], S], 1, sel ? 0.1 : ["get", "op"]]);
    map.setPaintProperty("stops-circle", "circle-radius", ["case", ["==", ["get", "vehicleId"], S], ["+", ["get", "r"], 2.5], ["get", "r"]]);
    map.setPaintProperty("stops-circle", "circle-stroke-width", ["case", ["==", ["get", "vehicleId"], S], 2.2, ["get", "stroke"]]);
  }
  if (map.getLayer("stops-label")) map.setFilter("stops-label", ["==", ["get", "vehicleId"], S]);
}

/**
 * A real WebGL map of the fleet (MapLibre GL + OpenFreeMap tiles), built to scale
 * to dozens of trucks: route legs + stops render as GeoJSON *layers* (not one DOM
 * marker each), the driven portion of every route is dimmed vs. the road still
 * ahead, and only moving vehicles get an animated arrow marker (idle vans stay at
 * the depot). The base map inits once; layer data + van markers rebuild on each
 * telemetry snapshot without reloading tiles.
 */
export function DispatchMap({
  telemetry,
  selected,
  onSelect,
  follow = false,
}: {
  telemetry: FleetTelemetrySnapshot;
  selected: string | null;
  onSelect: (id: string) => void;
  /** When set, the camera gently tracks the selected vehicle as it moves. */
  follow?: boolean;
}) {
  const containerRef = useRef<HTMLDivElement>(null);
  const mapRef = useRef<MlMap | null>(null);
  const mlRef = useRef<typeof import("maplibre-gl") | null>(null);
  const popupRef = useRef<import("maplibre-gl").Popup | null>(null);
  const loadedRef = useRef(false);
  // Latest telemetry, read by the selection effect so it can frame a route
  // without re-firing (and re-zooming) on every auto-play tick. Synced in an
  // effect (declared first, so it runs before the selection effect below).
  const telemetryRef = useRef(telemetry);
  const selectedRef = useRef(selected);
  useEffect(() => {
    telemetryRef.current = telemetry;
    selectedRef.current = selected;
  });
  // Persistent vehicle markers keyed by vehicle id. Each glides linearly from its
  // previous real position (`from`) to the latest one (`target`) over one refresh
  // interval, so a truck moves continuously at its true pace between refreshes
  // instead of racing to the stop. Markers persist (never recreated per tick).
  type VehMarker = { marker: MlMarker; from: [number, number]; target: [number, number]; setAt: number; status: string; selected: boolean };
  const vehMarkersRef = useRef<Map<string, VehMarker>>(new Map());
  const depotMarkerRef = useRef<MlMarker | null>(null);
  const [ready, setReady] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Init the map once.
  useEffect(() => {
    if (!webglSupported()) {
      // eslint-disable-next-line react-hooks/set-state-in-effect
      setError("This browser has no WebGL, which the map needs to render.");
      return;
    }
    let cancelled = false;
    let map: MlMap | null = null;
    let resizeObs: ResizeObserver | null = null;
    const vehStore = vehMarkersRef.current; // stable ref; cleared on teardown
    (async () => {
      try {
        const maplibregl = await import("maplibre-gl");
        if (cancelled || !containerRef.current) return;
        mlRef.current = maplibregl;
        maplibregl.setWorkerUrl("/maplibre/maplibre-gl-worker.mjs");
        map = new maplibregl.Map({
          container: containerRef.current,
          style: MAP_STYLE,
          center: [telemetry.depot.lng, telemetry.depot.lat],
          zoom: 10.2,
          attributionControl: { compact: true },
        });
        mapRef.current = map;
        map.addControl(new maplibregl.NavigationControl({ showCompass: false }), "top-right");
        const ro = new ResizeObserver(() => map?.resize());
        ro.observe(containerRef.current);
        resizeObs = ro;
        map.on("error", (e: { error?: { message?: string } }) => {
          const msg = e?.error?.message;
          if (!msg) return;
          console.warn("[fleet-map] map error:", msg);
          // Only a failure *before* the first successful load is fatal to the
          // panel. Post-load resource misses (a tile, a glyph for stop labels)
          // must never blank a working map.
          if (!cancelled && !loadedRef.current) setError(msg);
        });
        map.on("load", () => {
          if (cancelled || !map) return;
          loadedRef.current = true;
          map.addSource("routeLines", { type: "geojson", data: routeLinesGeoJSON(telemetry) });
          map.addSource("stops", { type: "geojson", data: stopsGeoJSON(telemetry) });

          // White casing beneath the SELECTED route only, so it reads as a bold,
          // outlined ribbon on top of the tangle of other routes.
          map.addLayer({
            id: "routes-casing",
            type: "line",
            source: "routeLines",
            filter: ["==", ["get", "vehicleId"], "__none__"],
            layout: { "line-cap": "round", "line-join": "round" },
            paint: { "line-color": "#ffffff", "line-width": 11, "line-opacity": 0.95, "line-blur": 0.4 },
          });
          // Driven portion: SOLID (the road already covered).
          map.addLayer({
            id: "routes-done",
            type: "line",
            source: "routeLines",
            filter: ["==", ["get", "done"], 1],
            layout: { "line-cap": "round", "line-join": "round" },
            paint: { "line-color": ["get", "color"], "line-width": 3, "line-opacity": 0.75 },
          });
          // Remaining road ahead: DOTTED (still to drive).
          map.addLayer({
            id: "routes-remaining",
            type: "line",
            source: "routeLines",
            filter: ["==", ["get", "done"], 0],
            layout: { "line-cap": "round", "line-join": "round" },
            paint: { "line-color": ["get", "color"], "line-width": 2.8, "line-opacity": 0.9, "line-dasharray": [0.4, 1.8] },
          });
          map.addLayer({
            id: "stops-circle",
            type: "circle",
            source: "stops",
            paint: {
              "circle-radius": ["get", "r"],
              "circle-color": ["get", "color"],
              "circle-opacity": ["get", "op"],
              "circle-stroke-width": ["get", "stroke"],
              // Route-colored ring so a stop still ties to its run at a glance.
              "circle-stroke-color": ["get", "routeColor"],
            },
          });
          // Sequence labels, shown only for the selected route to avoid clutter.
          map.addLayer({
            id: "stops-label",
            type: "symbol",
            source: "stops",
            filter: ["==", ["get", "vehicleId"], "__none__"],
            layout: {
              "text-field": ["to-string", ["get", "seq"]],
              "text-size": 12,
              "text-font": ["Noto Sans Regular"],
              "text-offset": [0, -1.2],
              "text-allow-overlap": true,
            },
            paint: { "text-color": "#0f172a", "text-halo-color": "#ffffff", "text-halo-width": 1.4 },
          });

          applyFocus(map, selected);

          const b = telemetry.bounds;
          map.fitBounds([[b.west, b.south], [b.east, b.north]], { padding: 48, duration: 0 });
          map.resize();
          requestAnimationFrame(() => map?.resize());
          setTimeout(() => map?.resize(), 300);

          // Click a stop -> popup with its details. Hover -> pointer cursor.
          const onStopClick = (e: MapMouseEvent & { features?: MapGeoJSONFeature[] }) => {
            const f = e.features?.[0];
            if (!f || !mlRef.current || !map) return;
            const p = f.properties as { customer?: string; address?: string; seq?: number; status?: string };
            const coords = (f.geometry as unknown as { coordinates: [number, number] }).coordinates;
            const label = String(p.status ?? "").replace(/_/g, " ").toLowerCase();
            popupRef.current?.remove();
            popupRef.current = new mlRef.current.Popup({ offset: 12 })
              .setLngLat(coords)
              .setHTML(
                `<div style="font:600 12px system-ui;margin-bottom:2px">${p.seq ? `#${p.seq} · ` : ""}${p.customer ?? "Stop"}</div>` +
                  `<div style="font:12px system-ui;color:#64748b">${p.address ?? ""}</div>` +
                  `<div style="font:11px system-ui;color:#64748b;text-transform:capitalize;margin-top:2px">${label}</div>`,
              )
              .addTo(map);
          };
          map.on("click", "stops-circle", onStopClick);
          map.on("mouseenter", "stops-circle", () => { if (map) map.getCanvas().style.cursor = "pointer"; });
          map.on("mouseleave", "stops-circle", () => { if (map) map.getCanvas().style.cursor = ""; });

          setReady(true);
        });
      } catch (err) {
        const msg = err instanceof Error ? err.message : "Map failed to load.";
        console.error("[fleet-map] init failed:", err);
        if (!cancelled) setError(msg);
      }
    })();
    return () => {
      cancelled = true;
      resizeObs?.disconnect();
      popupRef.current?.remove();
      map?.remove();
      mapRef.current = null;
      vehStore.clear();
      depotMarkerRef.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Reconcile layer data + vehicle markers whenever telemetry changes. Markers
  // persist and are retargeted (not recreated), so the smoothing loop can ease
  // each truck from where it is toward its new real position at its true pace.
  useEffect(() => {
    const map = mapRef.current;
    const maplibregl = mlRef.current;
    if (!map || !maplibregl || !ready) return;

    (map.getSource("routeLines") as GeoJSONSource | undefined)?.setData(routeLinesGeoJSON(telemetry) as never);
    (map.getSource("stops") as GeoJSONSource | undefined)?.setData(stopsGeoJSON(telemetry) as never);

    // Depot marker (created once).
    if (!depotMarkerRef.current) {
      const depotEl = document.createElement("div");
      depotEl.style.cssText =
        "width:16px;height:16px;background:#0ea5e9;border:2px solid #fff;transform:rotate(45deg);box-shadow:0 1px 3px rgba(0,0,0,.4)";
      depotMarkerRef.current = new maplibregl.Marker({ element: depotEl }).setLngLat([telemetry.depot.lng, telemetry.depot.lat]).addTo(map);
    }
    const idleCount = telemetry.vehicles.filter((v) => (v.telemetry?.status ?? "IDLE") === "IDLE").length;
    depotMarkerRef.current.setPopup(new maplibregl.Popup({ offset: 16 }).setText(`${telemetry.depot.name ?? "Depot"} — ${idleCount} parked`));

    // Reconcile a marker per moving van (en route / dropping off / returning).
    const store = vehMarkersRef.current;
    const seen = new Set<string>();
    for (const v of telemetry.vehicles) {
      const t = v.telemetry;
      if (!t || t.status === "IDLE") continue;
      seen.add(v.vehicle.id);
      const isSel = selected === v.vehicle.id;
      const color = VEHICLE_COLOR[t.status] ?? "#94a3b8";
      const target: [number, number] = [t.lng, t.lat];
      let entry = store.get(v.vehicle.id);
      // Create, or re-skin when status/selection changes (color/size differ).
      if (!entry || entry.status !== t.status || entry.selected !== isSel) {
        const at = (entry?.marker.getLngLat() ?? { lng: target[0], lat: target[1] });
        const from: [number, number] = [at.lng, at.lat];
        entry?.marker.remove();
        const el = vanEl(color, isSel);
        el.addEventListener("click", () => onSelect(v.vehicle.id));
        const marker = new maplibregl.Marker({ element: el, rotationAlignment: "map" }).setLngLat(from).setRotation(t.headingDeg).addTo(map);
        entry = { marker, from, target, setAt: performance.now(), status: t.status, selected: isSel };
        store.set(v.vehicle.id, entry);
      } else {
        // Retarget: glide from wherever the marker is now toward the new position.
        const at = entry.marker.getLngLat();
        entry.from = [at.lng, at.lat];
        entry.target = target;
        entry.setAt = performance.now();
        entry.marker.setRotation(t.headingDeg);
      }
    }
    // Drop markers for vehicles that stopped being tracked (went idle/parked).
    for (const [id, entry] of store) {
      if (!seen.has(id)) {
        entry.marker.remove();
        store.delete(id);
      }
    }
  }, [telemetry, ready, onSelect, selected]);

  // Smoothing loop: interpolate every vehicle marker linearly from its previous
  // real position toward the latest one over one refresh interval - continuous
  // motion at the truck's true pace (it advances only a little between refreshes,
  // because the day is real-time), never a dash to the next stop.
  useEffect(() => {
    if (!ready) return;
    let raf = 0;
    // A touch longer than the data refresh so a marker is still gliding when the
    // next position lands (then it retargets smoothly rather than pausing).
    const GLIDE_MS = 4300;
    const step = (now: number) => {
      for (const e of vehMarkersRef.current.values()) {
        const f = Math.min((now - e.setAt) / GLIDE_MS, 1);
        const lng = e.from[0] + (e.target[0] - e.from[0]) * f;
        const lat = e.from[1] + (e.target[1] - e.from[1]) * f;
        e.marker.setLngLat([lng, lat]);
      }
      raf = requestAnimationFrame(step);
    };
    raf = requestAnimationFrame(step);
    return () => cancelAnimationFrame(raf);
  }, [ready]);

  // Selection: focus the selected route (dim the rest) and frame its whole run.
  useEffect(() => {
    const map = mapRef.current;
    const maplibregl = mlRef.current;
    if (!map || !ready) return;
    applyFocus(map, selected);
    const tel = telemetryRef.current;
    if (selected && maplibregl) {
      const route = tel.routes.find((r) => r.vehicleId === selected);
      const v = tel.vehicles.find((x) => x.vehicle.id === selected);
      const bounds = new maplibregl.LngLatBounds();
      bounds.extend([tel.depot.lng, tel.depot.lat]);
      for (const s of route?.stops ?? []) bounds.extend([s.lng, s.lat]);
      if (v?.telemetry) bounds.extend([v.telemetry.lng, v.telemetry.lat]);
      if (!bounds.isEmpty()) {
        // Pad the right side so the route isn't hidden under the floating panel.
        map.fitBounds(bounds, { padding: { top: 70, bottom: 70, left: 70, right: 400 }, maxZoom: 14, duration: 700 });
      }
    } else {
      const b = tel.bounds;
      map.fitBounds([[b.west, b.south], [b.east, b.north]], { padding: 48, duration: 600 });
    }
  }, [selected, ready]);

  // Auto-follow: as the selected vehicle moves (each live refresh), gently pan the
  // camera to keep it centered. Keyed on telemetry only (reads selection via ref)
  // so it tracks motion but doesn't fight the initial route-framing on select.
  useEffect(() => {
    const map = mapRef.current;
    const sel = selectedRef.current;
    if (!map || !ready || !follow || !sel) return;
    const v = telemetry.vehicles.find((x) => x.vehicle.id === sel);
    const t = v?.telemetry;
    if (t && (t.status === "EN_ROUTE" || t.status === "RETURNING")) {
      map.easeTo({ center: [t.lng, t.lat], duration: 1400, essential: true });
    }
  }, [telemetry.vehicles, ready, follow]);

  return (
    <div className="relative h-full min-h-0 w-full overflow-hidden rounded-lg">
      <link rel="stylesheet" href={MAP_CSS_HREF} precedence="default" />
      <div
        ref={containerRef}
        className="h-full w-full"
        style={{ background: "var(--color-surface2)" }}
        role="img"
        aria-label="Live WebGL map of the delivery fleet across Austin, Texas"
      />
      {!ready && !error && (
        <div className="absolute inset-0 grid place-items-center">
          <div className="flex items-center gap-2 rounded-lg bg-black/5 px-3 py-2 text-xs text-muted backdrop-blur-sm dark:bg-white/5">
            <span className="size-3 animate-spin rounded-full border-2 border-current border-t-transparent" />
            Loading map…
          </div>
        </div>
      )}
      {error && (
        <div className="absolute inset-0 grid place-items-center p-4">
          <div className="max-w-sm rounded-xl border border-danger/40 bg-surface/95 p-4 text-center shadow-lg backdrop-blur-sm">
            <div className="text-sm font-semibold text-danger">Map couldn’t load</div>
            <p className="mt-1 wrap-break-word text-xs text-muted">{error}</p>
            <p className="mt-2 text-xs text-muted">The route list on the right is still live.</p>
          </div>
        </div>
      )}
    </div>
  );
}
