import { and, eq } from "drizzle-orm";
import { authenticate, requireScope } from "@/lib/public-api";
import { getPackage } from "@/lib/modules/inventory";
import { db } from "@/db";
import { products } from "@/db/schema";
import { simplePdf, pdfResponse } from "@/lib/pdf";

/**
 * GET /api/v1/packages/{id}/label - a printable package label PDF (Distru's
 * DistruLabels affordance, basic): product + SKU headline, the package tag, its
 * Metrc tag + barcode, quantity, status, and lab-testing state - what a picker
 * scans and reads off the shelf.
 */
export async function GET(req: Request, { params }: { params: Promise<{ id: string }> }) {
  const auth = await authenticate(req);
  if (auth instanceof Response) return auth;
  const scopeErr = requireScope(auth, "inventory:read");
  if (scopeErr) return scopeErr;
  const { id } = await params;

  const pkg = await getPackage(auth.ctx, id);
  if (!pkg) {
    return pdfResponse(simplePdf(`Package ${id}`, ["No data on file."]), `label-${id}`);
  }

  let productName = "Package";
  let sku = "-";
  if (pkg.productId) {
    const [p] = await db
      .select({ name: products.name, sku: products.sku })
      .from(products)
      .where(and(eq(products.organizationId, auth.ctx.orgId), eq(products.id, pkg.productId)))
      .limit(1);
    if (p) {
      productName = p.name;
      sku = p.sku ?? "-";
    }
  }

  const lines = [
    `SKU: ${sku}`,
    "",
    `Package: ${pkg.packageTag}`,
    ...(pkg.metrcTag ? [`Metrc Tag: ${pkg.metrcTag}`] : []),
    ...(pkg.barcode ? [`Barcode: ${pkg.barcode}`] : []),
    ...(pkg.serialNumber ? [`Serial: ${pkg.serialNumber}`] : []),
    "",
    `Quantity: ${Number(pkg.quantity)}`,
    `Status: ${pkg.status}`,
    ...(pkg.labTestingState ? [`Lab testing: ${pkg.labTestingState}`] : []),
    "",
    "Generated by Distru — not for resale without a compliant label.",
  ];
  return pdfResponse(simplePdf(productName, lines), `label-${pkg.packageTag}`);
}
